language: objective-c
osx_image: xcode7.1
branches:
  only:
    - master
notifications:
  email: false
script:
  - xcodebuild -project UBICoreDataTest/UBICoreDataTest.xcodeproj -scheme UBICoreDataTest -configuration Debug OBJROOT=build -sdk iphonesimulator clean test