language: objective-c
osx_image: xcode11.6
branches:
  only:
    - master
notifications:
  email: false
script:
  - xcodebuild -project UBICoreDataTest/UBICoreDataTest.xcodeproj -scheme UBICoreDataTest -configuration Debug OBJROOT=build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' clean test
