language: objective-c
osx_image: xcode7.1
branches:
  only:
    - master
notifications:
  email: false
script:
  - xcodebuild -project UBICoreDataTest/UBICoreDataTest.xcodeproj -scheme UBICoreDataTest -configuration Release OBJROOT=build -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES clean test